const express = require("express");
const router = express.Router();
const productsController = require("./productsController");
const author = require('../../routes/author/author');
router.get("/list-paint-items", productsController.listPaintItem);
router.post("/create-paint-item", productsController.createPaintItem);
router.get("/detail-paint-item", productsController.detailPaintItem);
router.post("/create-paint-export", productsController.createPaintExport);
router.get("/list-paint-export", productsController.listPaintExport);
router.get("/detail-paint-item/:id", productsController.detailPaintItem);
router.put("/update-paint-item/:id", productsController.updatePaintItem);
router.get("/detail-paint-export/:id", productsController.detailPaintExport);
router.delete("/delete-paint-items/:id", productsController.deletePaintItems);
router.delete("/delete-paint-export/:id", productsController.deletePaintExport);
router.get('/income-customer/:phone_number', productsController.incomeCustomer);
router.get('/statistical-income', productsController.statisticalIncome);
module.exports = router;
